### ISSUE TITLE
[Question]: "New Signing"

### ISSUE THREAD

**Issue by pzentner** [microsoft/AL-Go#1237]
### Question

I had some issues before and then it started working (I thought), however, it doesn't seem like it did, so I switched back. Now I finally want to make it work, so I switched to the "new way of signing" using the keyVaultCodeSignCertificateName". The certificate is in an Azure Key Vault and I gave the proper permissions to the service principal (I believe at least, since I got an error that the app didn't have sign permissions, so I added them and then didn't get any new permission error).

The setting for this is in the org variable, not in the repo settings files.

When it gets to the signing, I am now getting the following error - anyone have any idea how to resolve this?

```Installing signing tool version 0.9.1-beta.24123.2 in C:\Users\xxx\AppData\Local\Temp\SigningTool-529087030
  Invoking signing tool using clientId/clientSecret
  info: Sign.Core.ISigner[0]
        Submitting C:\1\_work\xxx\xxx\Customizations\.buildartifacts\Apps\NAV-X_XXX Customizations_1.1.15.1.app for signing.
  info: Sign.Core.ISigner[0]
        SignAsync called for C:\1\_work\xxx\xxx\Customizations\.buildartifacts\Apps\NAV-X_XXX Customizations_1.1.15.1.app. Using C:\Users\xxx\AppData\Local\Temp\5rdaanw4.mtu\40wp42t0.app locally.
  info: Sign.Core.ISignatureProvider[0]
        Signing SignTool job with 1 files.
  info: Sign.Core.ISignatureProvider[0]
        Signing C:\Users\xxx\AppData\Local\Temp\5rdaanw4.mtu\40wp42t0.app.
  fail: Sign.Core.ISignatureProvider[0]
        Signing failed with error -2146762[74](https://github.com/nav-x-llc/xxx/actions/runs/11153259692/job/31001014847#step:9:77)9.
  info: Sign.Core.ISignatureProvider[0]
        Performing attempt #2 of 3 attempts after 5 s.
  info: Sign.Core.ISignatureProvider[0]
        Signing C:\Users\xxx\AppData\Local\Temp\5rdaanw4.mtu\40wp42t0.app.
  fail: Sign.Core.ISignatureProvider[0]
        Signing failed with error -2147024864.
  info: Sign.Core.ISignatureProvider[0]
        Performing attempt #3 of 3 attempts after 11.1803398 s.
  info: Sign.Core.ISignatureProvider[0]
        Signing C:\Users\xxx\AppData\Local\Temp\5rdaanw4.mtu\40wp42t0.app.
  fail: Sign.Core.ISignatureProvider[0]
        Signing failed with error -2147024864.
  fail: Sign.Core.ISignatureProvider[0]
        Failed to sign. Attempts exceeded.
  warn: Sign.Core.IDirectoryService[0]
        An exception occurred while attempting to delete directory C:\Users\xxx\AppData\Local\Temp\5rdaanw4.mtu.
        System.IO.IOException: The process cannot access the file '40wp42t0.app' because it is being used by another process.
           at System.IO.FileSystem.RemoveDirectoryRecursive(String fullPath, WIN32_FIND_DATA& findData, Boolean topLevel)
           at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
           at Sign.Core.DirectoryService.Delete(DirectoryInfo directory) in /_/src/Sign.Core/FileSystem/DirectoryService.cs:line 52
  fail: Sign.Core.ISigner[0]
        Could not sign C:\Users\xxx\AppData\Local\Temp\5rdaanw4.mtu\40wp42t0.app.
        System.Exception: Could not sign C:\Users\xxx\AppData\Local\Temp\5rdaanw4.mtu\40wp42t0.app.
           at Sign.Core.AzureSignToolSignatureProvider.<>c__DisplayClass7_0.<<SignAsync>b__0>d.MoveNext() in /_/src/Sign.Core/SignatureProviders/AzureSignToolSignatureProvider.cs:line 110
        --- End of stack trace from previous location ---
           at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
        --- End of stack trace from previous location ---
           at Sign.Core.AzureSignToolSignatureProvider.SignAsync(IEnumerable`1 files, SignOptions options) in /_/src/Sign.Core/SignatureProviders/AzureSignToolSignatureProvider.cs:line 104
           at Sign.Core.AggregatingSignatureProvider.SignAsync(IEnumerable`1 files, SignOptions options) in /_/src/Sign.Core/SignatureProviders/AggregatingSignatureProvider.cs:line 204
           at Sign.Core.Signer.<>c__DisplayClass3_0.<<SignAsync>b__0>d.MoveNext() in /_/src/Sign.Core/Signer.cs:line 153
        --- End of stack trace from previous location ---
           at System.Threading.Tasks.Parallel.<>c__50`1.<<ForEachAsync>b__50_0>d.MoveNext()
        --- End of stack trace from previous location ---
           at Sign.Core.Signer.SignAsync(IReadOnlyList`1 inputFiles, String outputFile, FileInfo fileList, DirectoryInfo baseDirectory, String applicationName, String publisherName, String description, Uri descriptionUrl, Uri timestampUrl, Int32 maxConcurrency, HashAlgorithmName fileHashAlgorithm, HashAlgorithmName timestampHashAlgorithm) in /_/src/Sign.Core/Signer.cs:line [85](https://github.com/nav-x-llc/xxx/actions/runs/11153259692/job/31001014847#step:9:88)
Applying settings from C:\1\_work\xxx\xxx\.github\AL-Go-Settings.json
No settings found in C:\1\_work\xxx\xxx\.AL-Go\settings.json
No settings found in C:\1\_work\xxx\xxx\.github\CICD.settings.json
No settings found in C:\1\_work\xxx\xxx\.AL-Go\CICD.settings.json
No settings found in C:\1\_work\xxx\xxx\.AL-Go\pzentner.settings.json
```

**Comment by aholstrup1** [comment]
Is it a self-hosted runner? If yes, can you make sure you have [Microsoft Visual C++ 14 runtime](https://github.com/microsoft/AL-Go/blob/edaf8ee8c67a115755aafc469e066ff3c27e47d7/Scenarios/SelfHostedGitHubRunner.md?plain=1#L35) installed?

**Comment by pzentner** [comment]
@aholstrup1 
Well, thank you very much! I guess that was it - seems like it makes sense to rebuild the self-hosted runners every so often or go through manually and see what needs to be updated.

**Comment by aholstrup1** [comment]
I know there's been an update to the signing tool that will display a warning if it isn't installed instead of just failing like this. I'll try to see if we can uptake that.
